### ISSUE TITLE
Маршрути та розклади автобусiв

### ISSUE THREAD

**Issue by flame4ost** [flame4ost/SmelaTrainBus-Mobile#2]
- [ ] Користувач  може переглядати розклад та маршрути автобусiв;
- [ ]  Користувач може шукати маршрути;
- [ ]  Користувач може фiльтрувати  розклад та маршрути автобусiв;
- [ ]  Користувач може додавати певнi маршрути в обране.
